"""
iNaturalist family->genus hierarchy mapping and utilities.

Provides the family (superclass) -> genus (fine-class) mapping
loaded from taxonomy.json, and helper functions matching the
cifar100_hierarchy.py interface for SAEANALYSIS compatibility.
"""
import json
from pathlib import Path
from typing import Dict, List, Optional


# Path to taxonomy.json generated by download_inat.py
_TAXONOMY_PATH = Path(__file__).parent.parent.parent.parent / "data" / "datasets" / "inat_family_genus" / "taxonomy.json"

# Loaded lazily on first access
_INAT_SUPERCLASSES: Optional[Dict[str, List[str]]] = None
_FINE_TO_SUPER: Optional[Dict[str, str]] = None


def _load_taxonomy():
    """Load taxonomy.json and populate module-level mappings."""
    global _INAT_SUPERCLASSES, _FINE_TO_SUPER

    if _INAT_SUPERCLASSES is not None:
        return

    if not _TAXONOMY_PATH.exists():
        raise FileNotFoundError(
            f"iNaturalist taxonomy not found at {_TAXONOMY_PATH}. "
            "iNaturalist hierarchy JSON not found. Download wordnet.is_a.txt from https://image-net.org/"
        )

    with open(_TAXONOMY_PATH) as f:
        taxonomy = json.load(f)

    _INAT_SUPERCLASSES = {}
    _FINE_TO_SUPER = {}

    for family_name, family_info in taxonomy["families"].items():
        genera = [g["name"] for g in family_info["genera"]]
        _INAT_SUPERCLASSES[family_name] = genera
        for genus in genera:
            _FINE_TO_SUPER[genus] = family_name


def get_inat_superclasses() -> Dict[str, List[str]]:
    """Return family -> [genus, ...] mapping."""
    _load_taxonomy()
    return _INAT_SUPERCLASSES


def build_superclass_map(
    selected_classes: List[str],
    class_to_idx: Dict[str, int],
) -> Dict[int, str]:
    """
    Map each class index to its iNaturalist family (superclass) name.

    Args:
        selected_classes: List of genus names used in the experiment.
            May be prefixed with "inat_" (e.g., "inat_Corvus").
        class_to_idx: Mapping from class name to integer index.

    Returns:
        Dict mapping class_idx -> family name.
        Classes not found in hierarchy are mapped to "unknown".
    """
    _load_taxonomy()

    superclass_map: Dict[int, str] = {}
    for class_name in selected_classes:
        idx = class_to_idx.get(class_name)
        if idx is None:
            continue
        # Strip dataset prefix (e.g., "inat_Corvus" -> "Corvus")
        bare_name = class_name.split("_", 1)[1] if class_name.startswith("inat_") else class_name
        superclass_map[idx] = _FINE_TO_SUPER.get(bare_name, _FINE_TO_SUPER.get(class_name, "unknown"))
    return superclass_map


def get_superclass_groups(
    superclass_map: Dict[int, str],
) -> Dict[str, List[int]]:
    """
    Group class indices by their family (superclass).

    Args:
        superclass_map: Dict mapping class_idx -> family name
            (as returned by build_superclass_map).

    Returns:
        Dict mapping family name -> list of class indices.
    """
    groups: Dict[str, List[int]] = {}
    for class_idx, superclass_name in superclass_map.items():
        groups.setdefault(superclass_name, []).append(class_idx)
    for key in groups:
        groups[key].sort()
    return groups


def has_hierarchical_structure(
    superclass_map: Dict[int, str],
) -> bool:
    """
    Check whether the selected classes have meaningful hierarchical structure.

    Returns True if at least 2 classes share a common family,
    which is the minimum needed for within-superclass analyses.
    """
    groups = get_superclass_groups(superclass_map)
    return any(len(indices) >= 2 for indices in groups.values())
